version: "3"
services:

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    image: youtube-playlist-generator-client-img
    container_name: youtube-playlist-generator-client-container
    networks:
      - app-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    command: npm start
    stdin_open: true
    tty: true
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    image: youtube-playlist-generator-server-img
    container_name: youtube-playlist-generator-server-container
    networks:
      - app-network
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db
    environment:
      - YOUTUBE_API_KEY=$YOUTUBE_API_KEY
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=db
      - DB_NAME=$DB_NAME
      - NODE_ENV=development
    command: /usr/app/node_modules/.bin/nodemon -L src/index.js

  db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/data/db
    container_name: app-postgres
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
  
networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local